// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "ui_world.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `local:zappy/host-api`

__attribute__((__import_module__("local:zappy/host-api"), __import_name__("host-log")))
extern void __wasm_import_local_zappy_host_api_host_log(uint8_t *, size_t);

__attribute__((__import_module__("local:zappy/host-api"), __import_name__("host-system-command")))
extern void __wasm_import_local_zappy_host_api_host_system_command(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("local:zappy/host-api"), __import_name__("emit-event")))
extern void __wasm_import_local_zappy_host_api_emit_event(uint8_t *, size_t, uint8_t *, size_t);

// Exported Functions from `ui-world`



__attribute__((__weak__, __export_name__("cabi_post_update-module")))
void __wasm_export_exports_ui_world_update_module_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (48+3*sizeof(void*));
      (void) base;
      switch ((int32_t) (int32_t) *((uint8_t*) (base + 0))) {
        case 0: {
          break;
        }
        case 1: {
          if ((*((size_t*) (base + (2*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (base + sizeof(void*))));
          }
          break;
        }
        case 2: {
          if ((*((size_t*) (base + (2*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (base + sizeof(void*))));
          }
          break;
        }
      }
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_get-commands")))
void __wasm_export_exports_ui_world_get_commands_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (8*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + sizeof(void*)))) > 0) {
        free(*((uint8_t **) (base + 0)));
      }
      if ((*((size_t*) (base + (3*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + (2*sizeof(void*)))));
      }
      if ((*((size_t*) (base + (5*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + (4*sizeof(void*)))));
      }
      if ((*((size_t*) (base + (7*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + (6*sizeof(void*)))));
      }
    }
    free(ptr);
  }
}


__attribute__((__weak__, __export_name__("cabi_post_serialize")))
void __wasm_export_exports_ui_world_serialize_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}



// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void local_zappy_graphic_text_cmd_free(local_zappy_graphic_text_cmd_t *ptr) {
  ui_world_string_free(&ptr->text);
}

void local_zappy_graphic_option_sprite_source_free(local_zappy_graphic_option_sprite_source_t *ptr) {
  if (ptr->is_some) {
  }
}

void local_zappy_graphic_sprite_cmd_free(local_zappy_graphic_sprite_cmd_t *ptr) {
  ui_world_string_free(&ptr->path);
  local_zappy_graphic_option_sprite_source_free(&ptr->source);
}

void local_zappy_graphic_render_command_free(local_zappy_graphic_render_command_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      local_zappy_graphic_text_cmd_free(&ptr->val.text);
      break;
    }
    case 2: {
      local_zappy_graphic_sprite_cmd_free(&ptr->val.sprite);
      break;
    }
  }
}

void local_zappy_system_text_segment_free(local_zappy_system_text_segment_t *ptr) {
  ui_world_string_free(&ptr->text);
}

void local_zappy_host_api_text_segment_free(local_zappy_host_api_text_segment_t *ptr) {
  local_zappy_system_text_segment_free(ptr);
}

void ui_world_list_string_free(ui_world_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    ui_world_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      ui_world_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void local_zappy_host_api_list_text_segment_free(local_zappy_host_api_list_text_segment_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    local_zappy_host_api_text_segment_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      local_zappy_host_api_text_segment_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void local_zappy_input_list_input_action_free(local_zappy_input_list_input_action_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    local_zappy_input_input_action_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void local_zappy_input_input_state_free(local_zappy_input_input_state_t *ptr) {
  local_zappy_input_list_input_action_free(&ptr->actions);
  ui_world_string_free(&ptr->raw_chars);
}

void local_zappy_command_response_command_free(local_zappy_command_response_command_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void local_zappy_command_command_desc_free(local_zappy_command_command_desc_t *ptr) {
  ui_world_string_free(&ptr->module);
  ui_world_string_free(&ptr->name);
  ui_world_string_free(&ptr->options);
  ui_world_string_free(&ptr->help);
}

void ui_world_input_state_free(ui_world_input_state_t *ptr) {
  local_zappy_input_input_state_free(ptr);
}

void ui_world_render_command_free(ui_world_render_command_t *ptr) {
  local_zappy_graphic_render_command_free(ptr);
}

void ui_world_command_desc_free(ui_world_command_desc_t *ptr) {
  local_zappy_command_command_desc_free(ptr);
}

void ui_world_response_command_free(ui_world_response_command_t *ptr) {
  local_zappy_command_response_command_free(ptr);
}

void ui_world_text_segment_free(ui_world_text_segment_t *ptr) {
  local_zappy_system_text_segment_free(ptr);
}

void ui_world_list_render_command_free(ui_world_list_render_command_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    ui_world_render_command_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      ui_world_render_command_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void ui_world_list_command_desc_free(ui_world_list_command_desc_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    ui_world_command_desc_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      ui_world_command_desc_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void ui_world_list_text_segment_free(ui_world_list_text_segment_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    ui_world_text_segment_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      ui_world_text_segment_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void ui_world_list_u8_free(ui_world_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void ui_world_string_set(ui_world_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void ui_world_string_dup(ui_world_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void ui_world_string_dup_n(ui_world_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void ui_world_string_free(ui_world_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void local_zappy_host_api_host_log(ui_world_string_t *msg) {
  __wasm_import_local_zappy_host_api_host_log((uint8_t *) (*msg).ptr, (*msg).len);
}

void local_zappy_host_api_host_system_command(ui_world_string_t *cmd, ui_world_list_string_t *args, local_zappy_host_api_list_text_segment_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_local_zappy_host_api_host_system_command((uint8_t *) (*cmd).ptr, (*cmd).len, (uint8_t *) (*args).ptr, (*args).len, ptr);
  *ret = (local_zappy_host_api_list_text_segment_t) { (local_zappy_host_api_text_segment_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void local_zappy_host_api_emit_event(ui_world_string_t *event_name, ui_world_string_t *payload) {
  __wasm_import_local_zappy_host_api_emit_event((uint8_t *) (*event_name).ptr, (*event_name).len, (uint8_t *) (*payload).ptr, (*payload).len);
}

__attribute__((__export_name__("handle-input")))
void __wasm_export_exports_ui_world_handle_input(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  ui_world_input_state_t arg4 = (local_zappy_input_input_state_t) {
    (local_zappy_input_engine_context_t) arg,
    (local_zappy_input_list_input_action_t) (local_zappy_input_list_input_action_t) { (local_zappy_input_input_action_t*)(arg0), (arg1) },
    (ui_world_string_t) (ui_world_string_t) { (uint8_t*)(arg2), (arg3) },
  };
  exports_ui_world_handle_input(&arg4);
}

__attribute__((__export_name__("run-command")))
int32_t __wasm_export_exports_ui_world_run_command(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  ui_world_string_t arg3 = (ui_world_string_t) { (uint8_t*)(arg), (arg0) };
  ui_world_list_string_t arg4 = (ui_world_list_string_t) { (ui_world_string_t*)(arg1), (arg2) };
  ui_world_response_command_t ret;
  exports_ui_world_run_command(&arg3, &arg4, &ret);
  int32_t variant;
  switch ((int32_t) (ret).tag) {
    case 0: {
      variant = 0;
      break;
    }
    case 1: {
      variant = 1;
      break;
    }
    case 2: {
      variant = 2;
      break;
    }
  }
  return variant;
}

__attribute__((__export_name__("update-module")))
uint8_t * __wasm_export_exports_ui_world_update_module(float arg, float arg0, float arg1, float arg2) {
  ui_world_list_render_command_t ret;
  exports_ui_world_update_module(arg, arg0, arg1, arg2, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("get-commands")))
uint8_t * __wasm_export_exports_ui_world_get_commands(void) {
  ui_world_list_command_desc_t ret;
  exports_ui_world_get_commands(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("accept-log")))
void __wasm_export_exports_ui_world_accept_log(uint8_t * arg, size_t arg0) {
  ui_world_list_text_segment_t arg1 = (ui_world_list_text_segment_t) { (ui_world_text_segment_t*)(arg), (arg0) };
  exports_ui_world_accept_log(&arg1);
}

__attribute__((__export_name__("serialize")))
uint8_t * __wasm_export_exports_ui_world_serialize(void) {
  ui_world_list_u8_t ret;
  exports_ui_world_serialize(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("deserialize")))
void __wasm_export_exports_ui_world_deserialize(uint8_t * arg, size_t arg0) {
  ui_world_list_u8_t arg1 = (ui_world_list_u8_t) { (uint8_t*)(arg), (arg0) };
  exports_ui_world_deserialize(&arg1);
}

__attribute__((__export_name__("handle-event")))
void __wasm_export_exports_ui_world_handle_event(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  ui_world_string_t arg3 = (ui_world_string_t) { (uint8_t*)(arg), (arg0) };
  ui_world_string_t arg4 = (ui_world_string_t) { (uint8_t*)(arg1), (arg2) };
  exports_ui_world_handle_event(&arg3, &arg4);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_ui_world(void);
__attribute__((used))
void __component_type_object_force_link_ui_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_ui_world();
}
