// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_UI_WORLD_H
#define __BINDINGS_UI_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct ui_world_string_t {
  uint8_t*ptr;
  size_t len;
} ui_world_string_t;

typedef struct local_zappy_graphic_color_t {
  uint8_t   r;
  uint8_t   g;
  uint8_t   b;
  uint8_t   a;
} local_zappy_graphic_color_t;

typedef struct local_zappy_graphic_rect_cmd_t {
  float   x;
  float   y;
  float   w;
  float   h;
  local_zappy_graphic_color_t   color;
  float   rotation;
} local_zappy_graphic_rect_cmd_t;

typedef struct local_zappy_graphic_text_cmd_t {
  ui_world_string_t   text;
  float   x;
  float   y;
  float   size;
  local_zappy_graphic_color_t   color;
} local_zappy_graphic_text_cmd_t;

typedef struct local_zappy_graphic_sprite_source_t {
  float   x;
  float   y;
  float   w;
  float   h;
} local_zappy_graphic_sprite_source_t;

typedef struct {
  bool is_some;
  local_zappy_graphic_sprite_source_t val;
} local_zappy_graphic_option_sprite_source_t;

typedef struct local_zappy_graphic_sprite_cmd_t {
  ui_world_string_t   path;
  float   x;
  float   y;
  float   w;
  float   h;
  local_zappy_graphic_option_sprite_source_t   source;
  local_zappy_graphic_color_t   color;
  float   rotation;
  bool   flip_x;
  bool   flip_y;
} local_zappy_graphic_sprite_cmd_t;

typedef struct local_zappy_graphic_render_command_t {
  uint8_t tag;
  union {
    local_zappy_graphic_rect_cmd_t     rect;
    local_zappy_graphic_text_cmd_t     text;
    local_zappy_graphic_sprite_cmd_t     sprite;
  } val;
} local_zappy_graphic_render_command_t;

#define LOCAL_ZAPPY_GRAPHIC_RENDER_COMMAND_RECT 0
#define LOCAL_ZAPPY_GRAPHIC_RENDER_COMMAND_TEXT 1
#define LOCAL_ZAPPY_GRAPHIC_RENDER_COMMAND_SPRITE 2

typedef local_zappy_graphic_color_t local_zappy_system_color_t;

typedef struct local_zappy_system_text_segment_t {
  ui_world_string_t   text;
  local_zappy_system_color_t   color;
} local_zappy_system_text_segment_t;

typedef local_zappy_system_text_segment_t local_zappy_host_api_text_segment_t;

typedef struct {
  ui_world_string_t *ptr;
  size_t len;
} ui_world_list_string_t;

typedef struct {
  local_zappy_host_api_text_segment_t *ptr;
  size_t len;
} local_zappy_host_api_list_text_segment_t;

typedef uint8_t local_zappy_input_engine_context_t;

#define LOCAL_ZAPPY_INPUT_ENGINE_CONTEXT_GAMEPLAY 0
#define LOCAL_ZAPPY_INPUT_ENGINE_CONTEXT_UI_CONSOLE 1

typedef uint8_t local_zappy_input_input_action_t;

#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_TOGGLE_CONSOLE 0
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_NAVIGATE_UP 1
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_NAVIGATE_DOWN 2
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_SCROLL_UP 3
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_SCROLL_DOWN 4
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_CONFIRM 5
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_DELETE 6
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_MOVE_LEFT 7
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_MOVE_RIGHT 8
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_MOVE_UP 9
#define LOCAL_ZAPPY_INPUT_INPUT_ACTION_MOVE_DOWN 10

typedef struct {
  local_zappy_input_input_action_t *ptr;
  size_t len;
} local_zappy_input_list_input_action_t;

typedef struct local_zappy_input_input_state_t {
  local_zappy_input_engine_context_t   context;
  local_zappy_input_list_input_action_t   actions;
  ui_world_string_t   raw_chars;
} local_zappy_input_input_state_t;

typedef struct local_zappy_command_response_command_t {
  uint8_t tag;
} local_zappy_command_response_command_t;

#define LOCAL_ZAPPY_COMMAND_RESPONSE_COMMAND_OK 0
#define LOCAL_ZAPPY_COMMAND_RESPONSE_COMMAND_BAD_ARGUMENT 1
#define LOCAL_ZAPPY_COMMAND_RESPONSE_COMMAND_UNKNOWN 2

typedef struct local_zappy_command_command_desc_t {
  ui_world_string_t   module;
  ui_world_string_t   name;
  ui_world_string_t   options;
  ui_world_string_t   help;
} local_zappy_command_command_desc_t;

typedef local_zappy_input_engine_context_t ui_world_engine_context_t;

typedef local_zappy_input_input_action_t ui_world_input_action_t;

typedef local_zappy_input_input_state_t ui_world_input_state_t;

typedef local_zappy_graphic_render_command_t ui_world_render_command_t;

typedef local_zappy_command_command_desc_t ui_world_command_desc_t;

typedef local_zappy_command_response_command_t ui_world_response_command_t;

typedef local_zappy_system_text_segment_t ui_world_text_segment_t;

typedef struct {
  ui_world_render_command_t *ptr;
  size_t len;
} ui_world_list_render_command_t;

typedef struct {
  ui_world_command_desc_t *ptr;
  size_t len;
} ui_world_list_command_desc_t;

typedef struct {
  ui_world_text_segment_t *ptr;
  size_t len;
} ui_world_list_text_segment_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} ui_world_list_u8_t;

// Imported Functions from `local:zappy/host-api`
extern void local_zappy_host_api_host_log(ui_world_string_t *msg);
extern void local_zappy_host_api_host_system_command(ui_world_string_t *cmd, ui_world_list_string_t *args, local_zappy_host_api_list_text_segment_t *ret);
extern void local_zappy_host_api_emit_event(ui_world_string_t *event_name, ui_world_string_t *payload);

// Exported Functions from `ui-world`
void exports_ui_world_handle_input(ui_world_input_state_t *state);
void exports_ui_world_run_command(ui_world_string_t *cmd, ui_world_list_string_t *args, ui_world_response_command_t *ret);
void exports_ui_world_update_module(float time, float dt, float w, float h, ui_world_list_render_command_t *ret);
void exports_ui_world_get_commands(ui_world_list_command_desc_t *ret);
void exports_ui_world_accept_log(ui_world_list_text_segment_t *segments);
void exports_ui_world_serialize(ui_world_list_u8_t *ret);
void exports_ui_world_deserialize(ui_world_list_u8_t *state);
void exports_ui_world_handle_event(ui_world_string_t *event_name, ui_world_string_t *payload);

// Helper Functions

void local_zappy_graphic_text_cmd_free(local_zappy_graphic_text_cmd_t *ptr);

void local_zappy_graphic_option_sprite_source_free(local_zappy_graphic_option_sprite_source_t *ptr);

void local_zappy_graphic_sprite_cmd_free(local_zappy_graphic_sprite_cmd_t *ptr);

void local_zappy_graphic_render_command_free(local_zappy_graphic_render_command_t *ptr);

void local_zappy_system_text_segment_free(local_zappy_system_text_segment_t *ptr);

void local_zappy_host_api_text_segment_free(local_zappy_host_api_text_segment_t *ptr);

void ui_world_list_string_free(ui_world_list_string_t *ptr);

void local_zappy_host_api_list_text_segment_free(local_zappy_host_api_list_text_segment_t *ptr);

void local_zappy_input_list_input_action_free(local_zappy_input_list_input_action_t *ptr);

void local_zappy_input_input_state_free(local_zappy_input_input_state_t *ptr);

void local_zappy_command_response_command_free(local_zappy_command_response_command_t *ptr);

void local_zappy_command_command_desc_free(local_zappy_command_command_desc_t *ptr);

void ui_world_input_state_free(ui_world_input_state_t *ptr);

void ui_world_render_command_free(ui_world_render_command_t *ptr);

void ui_world_command_desc_free(ui_world_command_desc_t *ptr);

void ui_world_response_command_free(ui_world_response_command_t *ptr);

void ui_world_text_segment_free(ui_world_text_segment_t *ptr);

void ui_world_list_render_command_free(ui_world_list_render_command_t *ptr);

void ui_world_list_command_desc_free(ui_world_list_command_desc_t *ptr);

void ui_world_list_text_segment_free(ui_world_list_text_segment_t *ptr);

void ui_world_list_u8_free(ui_world_list_u8_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void ui_world_string_set(ui_world_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void ui_world_string_dup(ui_world_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void ui_world_string_dup_n(ui_world_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void ui_world_string_free(ui_world_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
